version: "3"

services:
  api:
    build: .
    env_file:
      - .env
    ports: 
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=rental-mgt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=wordpress
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-db:

