version: "3"
services:
  api:
    build: .
    env_file:
      - .env
    ports: 
      - 8000:8000
    volumes:
      - static:/api/static
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
  #   depends_on:
  #     - postgres  # Ensure that the FastAPI container starts after the PostgreSQL container
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_DB=rental-mgt
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=wordpress
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data

volumes:
  static:
  # postgres-db:
